export const MOCK_COURSES = [
    {
        id: 1,
        title: "Complete Web Development Bootcamp",
        instructor: "Dr. Angela Yu",
        price: 19.99,
        originalPrice: 29.99,
        rating: 4.8,
        reviews: 4503,
        image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&h=250&fit=crop",
        isBestseller: true,
        isNew: false,
        category: "Web Development",
        level: "Beginner"
    },
    {
        id: 2,
        title: "Machine Learning A-Z™: AI, Python & R",
        instructor: "Kirill Eremenko",
        price: 24.99,
        originalPrice: 39.99,
        rating: 4.7,
        reviews: 3200,
        image: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=400&h=250&fit=crop",
        isBestseller: true,
        isNew: false,
        category: "Data Science",
        level: "Intermediate"
    },
    {
        id: 3,
        title: "Graphic Design Masterclass",
        instructor: "Lindsay Marsh",
        price: 14.99,
        originalPrice: 24.99,
        rating: 4.9,
        reviews: 2100,
        image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=250&fit=crop",
        isBestseller: false,
        isNew: true,
        category: "Design",
        level: "All Levels"
    },
    {
        id: 4,
        title: "The Business Strategy Game",
        instructor: "Philip Kotler",
        price: 29.99,
        originalPrice: 49.99,
        rating: 4.6,
        reviews: 1800,
        image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=250&fit=crop",
        isBestseller: true,
        isNew: false,
        category: "Business",
        level: "Advanced"
    },
    {
        id: 5,
        title: "React & TypeScript — The Complete Guide",
        instructor: "Maximilian Schwarzmüller",
        price: 19.99,
        originalPrice: 34.99,
        rating: 4.8,
        reviews: 3750,
        image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400&h=250&fit=crop",
        isBestseller: true,
        isNew: false,
        category: "Web Development",
        level: "Intermediate"
    },
    {
        id: 6,
        title: "UI/UX Design Bootcamp 2026",
        instructor: "Sarah Johnson",
        price: 22.99,
        originalPrice: 39.99,
        rating: 4.7,
        reviews: 1450,
        image: "https://images.unsplash.com/photo-1541462608143-67571c6738dd?w=400&h=250&fit=crop",
        isBestseller: false,
        isNew: true,
        category: "Design",
        level: "Beginner"
    }
];
